site_name: Quam1123的笔记本
repo_url: https://github.com/requam1123/blog
repo_name: quam1123_blog
nav :
  - 首页: index.md
  # - What problems I meet: What Problems I meet？.md

  - CTF : 
    - CTF101课程 :
      - misc :
        - ctf/misc/index.md
        - misc_lab1 : ctf/misc/misc_lab1/misc_lab1.md
        - misc_lab2 : ctf/misc/misc_lab2/misc_lab2.md
        - misc_lab3 : ctf/misc/misc_lab3/misc_lab3.md
      - web :
        - ctf/web/index.md
        - web_lab1 : ctf/web/web_lab1/web_lab1.md
        - web_lab2 : ctf/web/web_lab2/web_lab2.md
        - web_lab3 : ctf/web/web_lab3/web_lab3.md
    - 偷偷刷题 : 
      - ctf/self/index.md

  - small tips: 
    - How_to_write_gitignore.md

  - 指令笔记本 :
    - ins/index.md
    - 网站操作 : ins/website/instruction_note.md
theme: 
  name: material 
  features:
    - navigation.tabs   # 导航标签 
    - navigation.tabs.sticky # 黏住
    - navigation.top    # 回到顶部
    - navigation.expand # 默认打开左侧导航所有小节
    - navigation.instant
    - navigation.instant.progress
    - navigation.tracking
    - navigation.sections
    - navigation.path
    - search.suggest
    - search.highlight
    - navigation.indexes
    # - toc.integrate
    # - header.autohide
    
  icon:
    repo: fontawesome/brands/github
    admonition:
      note: octicons/tag-16
      abstract: octicons/checklist-16
      info: octicons/info-16
      tip: octicons/squirrel-16
      success: octicons/check-16
      question: octicons/question-16
      warning: octicons/alert-16
      failure: octicons/x-circle-16
      danger: octicons/zap-16
      bug: octicons/bug-16
      example: octicons/beaker-16
      quote: octicons/quote-16

plugins:
  - search
markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js